apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: be
spec:
  replicas: 3 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: be
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - mysql
              topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - be
                topologyKey: kubernetes.io/hostname
      containers:
        - name: be
          image: k8s.gcr.io/pause:2.0
          ports:
            - containerPort: 4002
              name: be-server