apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ops
  name: ops
spec:
  containers:
  - image: nginx
    name: ops
    ports:
      - containerPort: 80
        name: http-server
    volumeMounts:
      - name: webcontentgreen
        mountPath: /nginx-green
      - name: webcontentblue
        mountPath: /nginx-blue
  volumes:
    - name: webcontentgreen
      gcePersistentDisk:
        pdName: webcontent-green
        fsType: ext4
    - name: webcontentblue
      gcePersistentDisk:
        pdName: webcontent-blue
        fsType: ext4
